Fix for support Instance::of in configuration
Codeception/module-yii2 pull request #21
Opened 2020-11-17 17:30 UTC by antonovsky

Using createObject with \yii\di\Instance::of in configuration does not work.
Creating an instance of the application in the suggested way solves the problem.

2020-11-18 10:20 UTC, SamMousa commented
This breaks instantiation using the DI container, therefore it is a BC break.

2020-11-18 11:28 UTC, antonovsky commented
I didn't create an issue. I posted this PR instead. Should I create an issue?

2020-11-18 11:36 UTC, SamMousa commented
No but some more explanation in here would be nice. This change breaks some existing behaviour so it needs to be motivated. Can it be fixed in another way without breaking instantiation via the container?

2020-11-18 11:40 UTC, antonovsky commented
> This breaks instantiation using the DI container, therefore it is a BC break.

What is BC?

2020-11-18 12:24 UTC, antonovsky commented
Why you think this breaks instantiation using the DI container? What do you mean? The tests in my project are still working correctly. DI work.

2020-11-18 14:45 UTC, SamMousa commented
> Why you think this breaks instantiation using the DI container? What do you mean? 

I'm sorry I was unclear.
It breaks instantiation of the application object itself via the DI container, because it no longer uses the DI container.


Your issue can actually be solved by putting this in the DI config, this wouldn't require any change to the module code.

```php
\yii\web\Application::class => static function(Container $c, array $params): \yii\web\Application {
    return new \yii\web\Application($params);
}
```

2020-11-18 15:40 UTC, antonovsky commented
My app config looks something like this. Did you mean this?
If I place your code in singletons or definitions, the error does not disappear:
Fatal error: Uncaught ReflectionException: Class MyComponentClassFromDI does not exist in /vendor/yiisoft/yii2/di/Container.php on line 449
```
[
    'container' => [
        'singletons' => [
            // singletons
            \yii\web\Application::class => static function(Container $c, array $params): \yii\web\Application {
                return new \yii\web\Application($params);
            },
            'MyComponentClassFromDI' => [
                'class' => app\components\MyComponentClassFromDI::class,
            ],
        ],

        'definitions' => [
            // definitions
        ],
    ],
    'components' => [
        'MyComponentClassFromDI' => \yii\di\Instance::of('MyComponentClassFromDI'),
    ],
  // other application configuration things
];
```

2020-11-18 15:52 UTC, antonovsky commented
I could be wrong, but i think at the time of the creation of the application itself, the DI container does not exist at all. Hence the problem with Instance::of().

2020-11-18 15:54 UTC, SamMousa commented
That depends on what is in your bootstrap.
I create the container before anything else, the container is then used to create the application object.

So that is what will break with your change.

2020-11-18 16:16 UTC, antonovsky commented
Thank you very much. If done in the way you suggested, everything will work.   
Last question: Why not let the application itself do the instantiation of the container?

2020-11-18 16:35 UTC, SamMousa commented
This is subjective, others might not share my opinion.

In my view the container consists outside the application and the method of configuring it via app config array is just a dirty hack so people can have all configuration in one place. https://github.com/yiisoft/yii2/blob/master/framework/Yii.php this file creates it as a side effect.

I don't use that file but instead use my own bootstrap that instantiates the container. Imo that's cleaner

2020-11-23 13:59 UTC, antonovsky commented
@SamMousa , How do you like this new revision? I think it works for all options.

2020-11-23 14:10 UTC, antonovsky commented
@SamMousa , Have you looked at the new code? The new version uses `createObject`  instead of `new Application`.  
That is, instead of changing the way the application object was created, I added `Yii::configure(Yii::$container, $config['container']);`

2020-11-23 14:12 UTC, SamMousa commented
Hmm, github shows just 1 file changed... and that is only the `Yii::configure` stuff... let me see if I can find a different diff...

2020-11-23 14:13 UTC, SamMousa commented
Ah wait, now I get it, you have reverted your old change so this is the full feature.

Yes, that looks good to me!

You take out container config and use that directly; feels like a clean solution to me!

2020-11-23 14:14 UTC, antonovsky commented
Yes, i change only 1 file (src/Codeception/Lib/Connector/Yii2.php):
```php
        if (isset($config['container']))
        {
            Yii::configure(Yii::$container, $config['container']);
            unset($config['container']);
        }
```

2020-11-23 22:12 UTC, samdark approved these changes

2020-11-23 22:14 UTC, samdark commented
Looks alright but we need to fix tests before merge to ensure it doesn't break things: https://github.com/Codeception/module-yii2/issues/22

2020-12-20 16:02 UTC, Naktibalda requested changes
Please rebase on master to get the tests passing.

2020-12-21 15:02 UTC, antonovsky commented
> Please rebase on master to get the tests passing.

done

2020-12-21 15:20 UTC, merged

2020-12-21 15:20 UTC, samdark commented
Thanks.